#!/bin/sh
#
# this script sets up a Subversion repository for Makefile in the
# first ever git merge, as if it were done with svnmerge.py
#

# where the script targets its commits
target=${1-branch}

if type -p svnmerge.py
then
   sm=svnmerge.py
else
   [ -f svnmerge.py ] ||
      wget http://svn.collab.net/repos/svn/trunk/contrib/client-side/svnmerge/svnmerge.py
   sm="python `pwd`/svnmerge.py"
fi

set -e

mkdir foo.svn
svnadmin create foo.svn
svn co file://`pwd`/foo.svn foo

cd foo
mkdir trunk
mkdir branches
svn add trunk branches
svn commit -m "Setup trunk and branches"
cd trunk

git-cat-file blob 6683463e:Makefile > Makefile
svn add Makefile 

echo "Committing ANCESTOR"
svn commit -m "ancestor"
cd ..
svn cp trunk branches/left

echo "Committing BRANCH POINT"
svn commit -m "make left branch"
cd branches/left/

$sm init
svn commit -m "init svnmerge"

git-cat-file blob 5873b67e:Makefile > Makefile
echo "Committing BRANCH UPDATE 1"
svn commit -m "left update 1"
cd ../..

if [ "$target" = "trunk" ]
then
    cd ../../trunk
    $sm init ../branches/left
    cd ..
    svn update
    svn commit -m "init svnmerge"
fi

cd trunk
git-cat-file blob 75118b13:Makefile > Makefile
echo "Committing TRUNK UPDATE"
svn commit -m "trunk update"

cd ../branches/left
git-cat-file blob ff5ebe39:Makefile > Makefile
echo "Committing BRANCH UPDATE 2"
svn commit -m "left update 2"

git-cat-file blob b5039db6:Makefile > Makefile
echo "Committing BRANCH UPDATE 3"
svn commit -m "left update 3"

if [ "$target" = "trunk" ]
then

    # check this crazy syntax out
    cd ../../trunk

    echo -n "available commits: "
    $sm avail

    # this bombs out.
    $sm merge

    git-cat-file blob b51ad431:Makefile > Makefile

    svn resolved Makefile
    svn update # ?!?!

    svn commit -m "merge branch 'left' into 'trunk'"

    cd ../..

else

    # merge to the branch

    echo -n "available commits: "
    $sm avail

    # this doesn't work
    $sm merge

    git-cat-file blob b51ad431:Makefile > Makefile

    svn resolved Makefile
    svn update # ?!?!

    svn commit -m "`cat svnmerge-commit-message.txt`"

    cd ../../..

fi

svnadmin dump foo.svn > svnmerge-merge.dump

rm -rf foo foo.svn

